# Generated by Django 3.0.5 on 2022-02-24 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=50)),
                ('date_ajoute', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(blank=True, max_length=50, null=True)),
                ('quantite_stock', models.IntegerField(blank=True, default='0', null=True)),
                ('alerte_quantite', models.IntegerField(blank=True, default='0', null=True)),
                ('date_ajoute', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_bd.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_stock', models.IntegerField(blank=True, default='0', null=True)),
                ('quantite_entrer', models.IntegerField(blank=True, default='0', null=True)),
                ('quantite_sortie', models.IntegerField(blank=True, default='0', null=True)),
                ('sortie_par', models.CharField(blank=True, max_length=50, null=True)),
                ('date_ajoute', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_bd.Produit')),
            ],
        ),
    ]
