# Generated by Django 3.0.5 on 2022-03-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_bd', '0004_auto_20220307_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='sortie_par',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
