# Generated by Django 3.0.5 on 2022-03-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_bd', '0006_auto_20220307_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='sortie_par',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
